In [1]:
import numpy as np
import tensorflow as tf

In [13]:
a = [1,2,3]
b = [-1,-2,-3]
c = zip(a, b)
{x:y for x,y in c}

{1: -1, 2: -2, 3: -3}

In [315]:
v = tf.transpose(tf.multinomial(tf.log([[.1, .9]]), 10))

sess = tf.Session()
with sess.as_default():
    tf.global_variables_initializer().run()
    v  = sess.run(v)

In [316]:
v

array([[1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]])

In [271]:
a1 = np.array([-1, -0.5, -0.5, 3])
b1 = np.std(a1)
c1 = np.mean(a1)
b1, c1

(1.6007810593582121, 0.25)

In [272]:
e1 = a1/b1# - (b1-b) 
d1 = e1-np.mean(e1)
d1, np.mean(d1), np.std(d1)

(array([-0.78086881, -0.46852129, -0.46852129,  1.71791138]),
 5.5511151231257827e-17,
 1.0)

In [273]:
e1 = (1-(b1-b))*a1/b1 
d1 = e1-np.mean(e1)
d1, np.mean(d1), np.std(d1)

(array([-0.08302644, -0.04981586, -0.04981586,  0.18265817]),
 0.0,
 0.10632572182833544)

In [274]:
e1 = (1-(b1-b))*a1/b1 
d1 = e1-np.mean(e1)
d1, np.mean(d1), np.std(d1), d1[-1]-d1[0]

(array([-0.08302644, -0.04981586, -0.04981586,  0.18265817]),
 0.0,
 0.10632572182833544,
 0.26568460741524202)

In [275]:
e1 = (1-(b1-b))*a1/b1 
d1 = e1-np.mean(e1)-c1
d1, np.mean(d1), np.std(d1), d1[-1]-d1[0]

(array([-0.33302644, -0.29981586, -0.29981586, -0.06734183]),
 -0.25,
 0.10632572182833544,
 0.26568460741524197)

In [267]:
c1

0.25

In [269]:
b1-b

0.89367427817166456

In [270]:
(1-(b1-b))

0.10632572182833544

In [238]:
0.91165111--0.45582555

1.36747666

In [7]:
for std in [2, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]:
    print('STD:', std, 1/std)
    a = np.array([1,0.5,0,1,0.01, -0.5,1, 0 ,0], dtype=np.float32)
    a_min = np.min(a, axis=-1, keepdims=True)
    a_max = np.max(a, axis=-1, keepdims=True)
    a_ = (a-a_min)/(a_max-a_min)
    s = np.std(a_, axis=-1)
    A=a_/np.expand_dims(std*s, 1)
    A = A - np.mean(A, axis=-1, keepdims=True)
    print("A:",A)
    print(np.std(A, axis=-1), np.mean(A, axis=-1), '\n')

STD: 2 0.5
A: [ 0.63223373  0.15726684 -0.31770009  0.63223373 -0.30820076 -0.79266702
  0.63223373 -0.31770009 -0.31770009]
0.500000008195 0.0 

STD: 10 0.1
A: [ 0.12644675  0.03145337 -0.06354002  0.12644675 -0.06164015 -0.1585334
  0.12644675 -0.06354002 -0.06354002]
0.100000001639 -4.62592926927e-18 

STD: 20 0.05
A: [ 0.06322337  0.01572668 -0.03177001  0.06322337 -0.03082008 -0.0792667
  0.06322337 -0.03177001 -0.03177001]
0.0500000008195 -2.31296463464e-18 

STD: 30 0.03333333333333333
A: [ 0.04214892  0.01048446 -0.02118001  0.04214892 -0.02054672 -0.05284447
  0.04214892 -0.02118001 -0.02118001]
0.0333333338797 5.39691748082e-18 

STD: 40 0.025
A: [ 0.03161169  0.00786334 -0.015885    0.03161169 -0.01541004 -0.03963335
  0.03161169 -0.015885   -0.015885  ]
0.0250000004098 -1.15648231732e-18 

STD: 50 0.02
A: [ 0.02528935  0.00629067 -0.012708    0.02528935 -0.01232803 -0.03170668
  0.02528935 -0.012708   -0.012708  ]
0.0200000003278 3.08395284618e-18 

STD: 60 0.01666666666666

/home/asi/anaconda3/envs/tensorflow/lib/python3.5/site-packages/ipykernel/__main__.py:8: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.


In [51]:
c = np.random.randn(5)
np.mean(c-np.mean(c))

4.4408920985006264e-17