In [1]:
import numpy as np
import tensorflow as tf

In [21]:
tf.reset_default_graph()
rand1 = tf.multinomial(tf.log([[1-0.2, 0.2]]), 10)
rand_choice1 = tf.cast(tf.less(tf.transpose(rand1), 1), tf.float32) 

rand2 = tf.multinomial(tf.log([[0.2, 1-0.2]]), 10)
rand_choice2 = tf.cast(tf.less(tf.transpose(rand2), 1), tf.float32) 
    
sess=tf.Session()
with sess.as_default():
    tf.global_variables_initializer().run()
    rand1, rand_choice1, rand2, rand_choice2  = sess.run([rand1, rand_choice1, rand2, rand_choice2])

In [22]:
rand1

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
rand2

array([[1, 1, 1, 0, 1, 1, 1, 0, 1, 1]])

In [26]:
rand_choice1, rand_choice1.shape

(array([[ 1.],
        [ 1.],
        [ 0.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.]], dtype=float32), (10, 1))

In [25]:
rand_choice2

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.]], dtype=float32)

In [93]:
tf.reset_default_graph()
with tf.device('/cpu:0'):
    sess = tf.Session()
    v = tf.Variable(np.random.randn(5,4,3))
    z = tf.Variable(np.random.randn(5,3))
    pool = tf.reduce_max(v, axis=1)
    g = tf.gradients(pool*z, [v])
    
    with sess.as_default():
        tf.global_variables_initializer().run()
        z,v, pool, g  = sess.run([z,v,pool,g])

In [94]:
v

array([[[  9.66329468e-02,   8.56943490e-01,  -1.13429013e+00],
        [  1.76360662e-01,  -7.80081574e-01,  -2.24211635e-01],
        [  2.59482516e+00,  -1.47262563e+00,  -6.58419029e-01],
        [ -1.43945423e+00,   2.28367045e-01,   7.57987704e-01]],

       [[ -1.48293777e+00,   6.69543265e-01,   1.33891190e+00],
        [  1.36286205e+00,  -1.50032347e+00,   5.33523025e-04],
        [  3.35798777e-01,   1.16708571e+00,  -2.54980434e+00],
        [  2.89748749e-01,  -2.11065238e-01,  -2.58823724e+00]],

       [[  2.01702482e+00,   2.30004762e+00,  -9.03874130e-01],
        [  5.57252685e-01,   5.08004502e-01,  -6.07645203e-01],
        [ -3.14329769e-01,   1.47917800e+00,  -3.41570588e-01],
        [  1.24272925e+00,   1.15362731e+00,  -6.36580593e-01]],

       [[  7.90080369e-01,  -1.03750042e-01,   8.07389158e-01],
        [ -1.53120415e+00,  -3.14797666e-03,   3.12905808e+00],
        [ -2.78078332e-02,  -2.36240934e-01,   3.57977180e-03],
        [ -9.42270892e-01,  -1.487

In [95]:
pool

array([[ 2.59482516,  0.85694349,  0.7579877 ],
       [ 1.36286205,  1.16708571,  1.3389119 ],
       [ 2.01702482,  2.30004762, -0.34157059],
       [ 0.79008037, -0.00314798,  3.12905808],
       [ 0.90963124, -0.11363754,  0.85764909]])

In [96]:
pool.shape

(5, 3)

In [97]:
g

[array([[[-0.        , -0.04154767,  0.        ],
         [-0.        , -0.        ,  0.        ],
         [-0.11962198, -0.        ,  0.        ],
         [-0.        , -0.        ,  0.57389386]],
 
        [[-0.        , -0.        ,  0.20937453],
         [-2.39905442, -0.        ,  0.        ],
         [-0.        , -0.03759407,  0.        ],
         [-0.        , -0.        ,  0.        ]],
 
        [[-1.3163498 ,  0.98069193,  0.        ],
         [-0.        ,  0.        ,  0.        ],
         [-0.        ,  0.        ,  0.87753507],
         [-0.        ,  0.        ,  0.        ]],
 
        [[ 0.56734216,  0.        ,  0.        ],
         [ 0.        ,  0.41682648,  2.15214067],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],
 
        [[-0.47925754,  0.        , -0.        ],
         [-0.        ,  0.        , -0.        ],
         [-0.        ,  0.        , -0.33252851],
         [-0.        ,  0.14240748, -0

In [98]:
z

array([[-0.11962198, -0.04154767,  0.57389386],
       [-2.39905442, -0.03759407,  0.20937453],
       [-1.3163498 ,  0.98069193,  0.87753507],
       [ 0.56734216,  0.41682648,  2.15214067],
       [-0.47925754,  0.14240748, -0.33252851]])