In [1]:
import tensorflow as tf
import numpy as np
import json

In [8]:
a = np.float32(0.5)
print(np.isnan(a), type(a))

False <class 'numpy.float32'>


In [110]:
# w2c words vectors
embed_vecs = np.load(open(embed_path, 'rb')).astype(np.float32)

with open(vocab_file, 'r') as f:
    vocab = json.loads(f.read())
vocab['<unk>'] = len(vocab)

print("Number of words:", len(vocab))

Number of words: 8242


In [94]:
tf.reset_default_graph()

with tf.variable_scope('w2v'):
            w2v_embed = tf.get_variable('w2v_embed', initializer=embed_vecs, trainable=False)
            w2v_queries = tf.nn.embedding_lookup(w2v_embed, self.queries, name='w2v_queries')

# embed is the trainable embedding matrix
with tf.variable_scope('embed'):
    embed = tf.get_variable('embed', shape=[voc_size, self.embed_size], 
                            initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1))
    embed_queries_tmp = tf.nn.embedding_lookup(embed, self.queries, name='embed_queries')


sess = tf.Session()
with sess.as_default():
    tf.global_variables_initializer().run()
    embed_queries, outputs, last_states = sess.run([embed_queries, outputs, last_states])

In [104]:
a = [1,2,3]
print(a)
a.insert(1, -123)
print(a)

[1, 2, 3]
[1, -123, 2, 3]


In [95]:
outputs

array([[[ 0.06084399,  0.0768529 , -0.03049651],
        [-0.20421889,  0.13484994,  0.01244315],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        

In [83]:
tf.reset_default_graph()

batch_size = 4
attn_size = 3
attn_dims = 2
num_units = 5

v = tf.Variable(np.random.randn(batch_size, attn_size, attn_dims), name = 'v', dtype=tf.float32)
attn_vecs = tf.reshape(v, [batch_size, attn_size, 1, attn_dims])
W = tf.get_variable("attn_W", [1, 1, attn_dims, num_units]) #[filter_height, filter_width, in_channels, out_channels] (filter)
hidden_attn = tf.nn.conv2d(attn_vecs, W, [1, 1, 1, 1], "SAME")

x = tf.Variable(np.array([1,2,3,4,5]), name = 'x', dtype=tf.float32)
logits = tf.reduce_sum(x*hidden_attn, [2,3])
max_logits = tf.reduce_max(logits, axis=-1)
masked_logits = tf.exp(logits-tf.expand_dims(max_logits, axis=1))
alpha = masked_logits/tf.reduce_sum(masked_logits, axis=-1, keep_dims=True)

a = tf.reshape(alpha, [-1, attn_size, 1, 1]) * attn_vecs

sess = tf.Session()
with sess.as_default():
    tf.global_variables_initializer().run()
    a, alpha, masked_logits, max_logits, logits, v, attn_vecs, W, hidden_attn = sess.run([a, alpha, masked_logits, max_logits, logits, v, attn_vecs, W, hidden_attn])

In [84]:
hidden_attn  

array([[[[ -1.37593257e+00,   6.00691698e-02,  -3.25912356e-01,
            6.63052797e-01,  -6.85074449e-01]],

        [[ -1.99990106e+00,   2.49359012e-01,  -3.44775528e-01,
            9.44926739e-01,  -1.02865183e+00]],

        [[  1.61426142e-01,   7.67133310e-02,   1.04880467e-01,
           -8.75139534e-02,   6.33659288e-02]]],


       [[[ -4.97249812e-01,  -5.80771089e-01,  -5.97143233e-01,
            3.09563190e-01,  -1.25244543e-01]],

        [[  1.65966117e+00,  -2.74857342e-01,   2.32077956e-01,
           -7.76282966e-01,   8.67440641e-01]],

        [[  3.61015677e-01,   7.44943768e-02,   1.57323897e-01,
           -1.84448764e-01,   1.61422461e-01]]],


       [[[  5.40452242e-01,  -4.61005598e-01,  -2.20010012e-01,
           -2.09661350e-01,   3.57907832e-01]],

        [[ -1.48224163e+00,  -1.54925976e-02,  -4.14906651e-01,
            7.23593175e-01,  -7.21720099e-01]],

        [[  1.16677487e+00,   1.45265681e-03,   3.18054348e-01,
           -5.68343043e-01, 

In [85]:
logits

array([[-3.00669241, -3.89906168,  0.59626806],
       [-2.83819151,  3.0382514 ,  1.05129337],
       [-0.09069538, -3.47217488,  2.70195627],
       [ 2.56409335, -5.11502266,  0.49286211]], dtype=float32)

In [86]:
max_logits

array([ 0.59626806,  3.0382514 ,  2.70195627,  2.56409335], dtype=float32)

In [87]:
masked_logits

array([[  2.72429474e-02,   1.11609986e-02,   1.00000000e+00],
       [  2.80474429e-03,   1.00000000e+00,   1.37111887e-01],
       [  6.12585619e-02,   2.08261423e-03,   1.00000000e+00],
       [  1.00000000e+00,   4.62383352e-04,   1.26030505e-01]], dtype=float32)

In [88]:
alpha

array([[  2.62354035e-02,   1.07482243e-02,   9.63016331e-01],
       [  2.46048183e-03,   8.77257109e-01,   1.20282382e-01],
       [  5.76095097e-02,   1.95855694e-03,   9.40431952e-01],
       [  8.87710810e-01,   4.10462701e-04,   1.11878641e-01]], dtype=float32)

In [89]:
a

array([[[[ -2.36754753e-02,  -2.00082399e-02]],

        [[ -9.64023080e-03,  -1.64335314e-02]],

        [[  3.08406979e-01,  -1.23127185e-01]]],


       [[[ -4.59646620e-03,   3.16814799e-03]],

        [[  5.00462234e-01,   1.26769555e+00]],

        [[  5.62653057e-02,  -4.09918511e-03]]],


       [[[ -4.40740399e-02,   8.26401487e-02]],

        [[ -2.30604503e-03,  -1.20151264e-03]],

        [[  8.45762730e-01,   4.80350733e-01]]],


       [[[  4.38146770e-01,   1.06135857e+00]],

        [[ -4.34755493e-04,  -9.18518926e-04]],

        [[  1.67447142e-02,   1.36014679e-02]]]], dtype=float32)

In [90]:
r1.shape, r2.shape, hidden_attn.shape, a.shape

((4, 3), (4, 3), (4, 3, 1, 5), (4, 3, 1, 2))

In [30]:
print(v)
print('\n', v)
print(type(v[0][0][0]))

[[[ 0.98496509 -0.02851603]
  [-1.66726875  0.26753381]
  [ 1.51515627 -1.50682473]]

 [[-0.4010278  -0.20075859]
  [ 2.04382253  0.63284922]
  [ 0.28390208 -0.73765641]]

 [[ 0.48980576 -0.38248792]
  [ 0.77407116 -0.76873422]
  [ 1.21942866 -0.62619776]]

 [[-0.50401235  0.96489722]
  [-1.17172551 -0.13353828]
  [ 0.46496364 -0.52199084]]]

 [[[ 0.98496509 -0.02851603]
  [-1.66726875  0.26753381]
  [ 1.51515627 -1.50682473]]

 [[-0.4010278  -0.20075859]
  [ 2.04382253  0.63284922]
  [ 0.28390208 -0.73765641]]

 [[ 0.48980576 -0.38248792]
  [ 0.77407116 -0.76873422]
  [ 1.21942866 -0.62619776]]

 [[-0.50401235  0.96489722]
  [-1.17172551 -0.13353828]
  [ 0.46496364 -0.52199084]]]
<class 'numpy.float32'>


In [31]:
print(attn_vecs)
print('\n', attn_vecs.shape)
print(type(attn_vecs[0][0][0]))

[[[[ 0.98496509 -0.02851603]]

  [[-1.66726875  0.26753381]]

  [[ 1.51515627 -1.50682473]]]


 [[[-0.4010278  -0.20075859]]

  [[ 2.04382253  0.63284922]]

  [[ 0.28390208 -0.73765641]]]


 [[[ 0.48980576 -0.38248792]]

  [[ 0.77407116 -0.76873422]]

  [[ 1.21942866 -0.62619776]]]


 [[[-0.50401235  0.96489722]]

  [[-1.17172551 -0.13353828]]

  [[ 0.46496364 -0.52199084]]]]

 (4, 3, 1, 2)
<class 'numpy.ndarray'>


In [32]:
print(W)
print('\n', W.shape)
print(type(W[0][0][0][0]))

[[[[ 0.7487042  -0.41131687 -0.19210237 -0.3272444   0.64037955]
   [-0.89684075  0.04162115 -0.88145727 -0.16965276 -0.38242561]]]]

 (1, 1, 2, 5)
<class 'numpy.float32'>


In [34]:
print(hidden_attn)
print('\n', hidden_attn.shape)
print(type(attn_vecs[0][0][0]))

[[[[  7.63021827e-01  -4.06319648e-01  -1.64078459e-01  -3.17486495e-01
      6.41656756e-01]]

  [[ -1.48822641e+00   6.96910799e-01   8.44666511e-02   5.00216484e-01
     -1.16999650e+00]]

  [[  2.48578572e+00  -6.85925126e-01   1.03713644e+00  -2.40189418e-01
      1.54652345e+00]]]


 [[[ -1.20202698e-01   1.56593710e-01   2.53998518e-01   1.65293351e-01
     -1.80034786e-01]]

  [[  9.62653518e-01  -8.14318776e-01  -9.50452685e-01  -7.76194096e-01
      1.06680441e+00]]

  [[  8.74118984e-01  -1.47475824e-01   5.95674336e-01   3.22400816e-02
      4.63903785e-01]]]


 [[[  7.09750414e-01  -2.17384949e-01   2.43053913e-01  -9.53960568e-02
      4.59934741e-01]]

  [[  1.26898253e+00  -3.50384116e-01   5.28905451e-01  -1.22892559e-01
      7.89682984e-01]]

  [[  1.47459102e+00  -5.27634680e-01   3.17711443e-01  -2.92815000e-01
      1.02037120e+00]]]


 [[[ -1.24271536e+00   2.47468919e-01  -7.53693700e-01   1.23774062e-03
     -6.91760600e-01]]

  [[ -7.57513285e-01   4.76392448e